apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-app
        image: docker-registry/dev-image:latest
        ports:
        - containerPort: 8080
