apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dev-app
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: dev-app
  targetCPUUtilizationPercentage: 50
