apiVersion: v1
kind: Pod
metadata:
  name: dev-app-readiness-pod
  labels:
    app: dev-app
spec:
  containers:
  - name: dev-app-container
    image: dev-image:latest
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
